name: "build"
on:
  push:
    branches: [ "**" ]
jobs:
  build:
    strategy:
      matrix:
        java: [ "21" ]
        os: [ "ubuntu-latest" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v4"
      - name: "validate gradle wrapper"
        uses: gradle/wrapper-validation-action@v3
      - name: "setup jdk ${{ matrix.java }}"
        uses: "actions/setup-java@v4"
        with:
          distribution: 'temurin'
          java-version: "${{ matrix.java }}"
      - name: "configure git"
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: "setup gradle"
        uses: gradle/gradle-build-action@v3
      - name: "apply patches"
        run: "git submodule update --init && ./gradlew applyPatches"
      - name: "build"
        working-directory: "patched-geyser"
        run: "./gradlew build -x check"

      - name: Archive artifacts (Geyser Fabric)
        # See https://github.com/actions/upload-artifact/commits
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4
        if: success()
        with:
          name: Geyser Fabric
          path: patched-geyser/bootstrap/mod/fabric/build/libs/Geyser-Fabric.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser NeoForge)
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4
        if: success()
        with:
          name: Geyser NeoForge
          path: patched-geyser/bootstrap/mod/neoforge/build/libs/Geyser-NeoForge.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4
        if: success()
        with:
          name: Geyser Standalone
          path: patched-geyser/bootstrap/standalone/build/libs/Geyser-Standalone.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4
        if: success()
        with:
          name: Geyser Spigot
          path: patched-geyser/bootstrap/spigot/build/libs/Geyser-Spigot.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4
        if: success()
        with:
          name: Geyser BungeeCord
          path: patched-geyser/bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4
        if: success()
        with:
          name: Geyser Velocity
          path: patched-geyser/bootstrap/velocity/build/libs/Geyser-Velocity.jar
          if-no-files-found: error
      - name: Archive artifacts (Geyser ViaProxy)
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4
        if: success()
        with:
          name: Geyser ViaProxy
          path: patched-geyser/bootstrap/viaproxy/build/libs/Geyser-ViaProxy.jar
          if-no-files-found: error
      - name: Publish to Maven Repository
        if: ${{ success() && github.repository == 'Kalimero2Team/Thermalquelle' && (github.ref_name == 'dev' || github.ref_name == 'main') }}
        working-directory: "patched-geyser"
        env:
          ORG_GRADLE_PROJECT_kalimero2Username: ${{ secrets.KALIMERO2_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_kalimero2Password: ${{ secrets.KALIMERO2_REPO_SECRET }}
        run: "./gradlew publish"
      - name: "Create (Dev Branch) Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ success() && github.repository == 'Kalimero2Team/Thermalquelle' && (github.ref_name == 'dev') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-dev"
          prerelease: true
          title: "Development Build"
          files: |
            patched-geyser/bootstrap/mod/fabric/build/libs/Geyser-Fabric.jar
            patched-geyser/bootstrap/mod/neoforge/build/libs/Geyser-NeoForge.jar
            patched-geyser/bootstrap/standalone/build/libs/Geyser-Standalone.jar
            patched-geyser/bootstrap/spigot/build/libs/Geyser-Spigot.jar
            patched-geyser/bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
            patched-geyser/bootstrap/velocity/build/libs/Geyser-Velocity.jar
            patched-geyser/bootstrap/viaproxy/build/libs/Geyser-ViaProxy.jar
