name: "test"
on:
  push:
    branches: [ "**" ]
jobs:
  build:
    strategy:
      matrix:
        java: [ "17" , "21" ]
        os: [ "ubuntu-latest" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v4"
      - name: "validate gradle wrapper"
        uses: gradle/wrapper-validation-action@v2
      - name: "setup jdk ${{ matrix.java }}"
        uses: "actions/setup-java@v4"
        with:
          distribution: 'temurin'
          java-version: "${{ matrix.java }}"
      - name: "configure git"
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: "setup gradle"
        uses: gradle/gradle-build-action@v3
      - name: "apply patches"
        run: "git submodule update --init && ./gradlew applyPatches"
      - name: "build"
        working-directory: "patched-geyser"
        run: "./gradlew build check"
